### ISSUE TITLE
Parse price and offer sorting by price (optionally at volume)

### ISSUE THREAD

**Issue by m1geo** [Joeskaife/JLCQT#4]
It would be nice to find the lowest price part that would do.

For example, the cheapest 0402 100nF cap, when ordered in 200 quantity. Otherwise, just seeing the cheapest part.

**Comment by m1geo** [comment]
Maybe this is already done? I just see the "sort" button cycles and includes price.

**Comment by Joeskaife** [comment]
Yeah, the cycling of sort policy is a bit, er, lacking in clarity!!
