### ISSUE TITLE
Table doesn't show manufacturer or MPN

### ISSUE THREAD

**Issue by m1geo** [Joeskaife/JLCQT#6]
For this random part, I see this:
![image](https://user-images.githubusercontent.com/758615/154513540-9e1fd301-08f8-4194-a3f9-fe205677f041.png)

However, in the official website, I see:
![image](https://user-images.githubusercontent.com/758615/154513883-32c4186b-3dac-47a5-94b0-d1c6c4fa4bf1.png)

It would be useful to show the manufacturer and the manufacturer part number.

**Comment by Joeskaife** [comment]
Added both manufacturer and manufacturer part number to the same column.
